services:
  openeft:
    container_name: "openeft"
    image: robbstumpf/eftsuite:latest
    restart: unless-stopped
    ports:
      - "8080:8080" #you can change the first port ("8080":8080) to whatever port you would like to expose on the host. By default, it is 8080
    volumes:
      - "./data:/app/temp" #OPTIONAL: this will mount the temp dir where generated eft files are stored.
    logging: #all logging config is optional too
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
